scaner/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^scan/$', views.create, name='scan'),
]

scanner/urls.py
from django.conf.urls import url

from . import views

app_name = 'scanner'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^scan/$', views.create, name='scan'),
    url(r'^about/$', views.about, name='about'),
    url(r'^ajax/scan_photo/$', views.scanPhoto, name='scan_photo'),
    url(r'^ajax/make_chart/$', views.makeChart, name='make_chart'),
]

vk_scaner_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^scaner/', include('scaner.urls')),
    url(r'^admin/', admin.site.urls),
]

vk_scanner_server/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^scanner/', include('scanner.urls')),
    url(r'^admin/', admin.site.urls),
]

scanner/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib import admin
from django.utils.html import format_html

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    link = models.CharField(max_length=150, blank=True)
    access_token = models.CharField(max_length=150, blank=True)

# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

class Person(models.Model):
    social_id = models.CharField(max_length=250)
    name = models.CharField(max_length=250)
    surname = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return "{} {}".format(self.name, self.surname)

class Photo(models.Model):
    url = models.CharField(max_length=250)
    labels = models.TextField()
    person = models.ForeignKey(Person, on_delete=models.CASCADE)

@admin.register(Photo)    
class PhotoAdmin(admin.ModelAdmin):
    
    list_display = ('url', 'labels', 'person', 'image')    
    
    def image(self, obj):
        return format_html(
            '<img src="{}">',
            obj.url
        )

    image.admin_order_field = 'image'

    def __str__(self):
        return self.url

scanner/views.py
from django.shortcuts import render
from scanner.models import Person, Photo
from django.http import HttpResponse, JsonResponse
from django.db.models import Q

import requests
import vk
from io import BytesIO
from photoGrabber import PhotoGrabber
from classify_image import run_inference_on_image
import matplotlib
matplotlib.use('Agg')
from matplotlib import pyplot as plt
from collections import Counter
import json

empty_label=json.dumps("-empty-")
# Create your views here.
def index(request):
    return render(request, 'index.html')

def login(request):
    code = request.GET.get('code', "")
    
    url = "https://oauth.vk.com/access_token"
    params = {"client_id": "6258947",
                "client_secret" : "7m6jlVFSkE4QgWT3528l",
                "redirect_uri" : "https://safe-everglades-40623.herokuapp.com/scanner/login",
                "code" : code
                }
    response = requests.get(url, params = params)
    response = response.json()
    token=""
    if "access_token" in response:
        token = response["access_token"]
        session = vk.Session()
        vkapi = vk.API(access_token=token, session = session)
        id = str(vkapi.users.get()[0]["uid"])
        request.session["vk_uid"]=id
        request.session["access_token"] = token
    return render(request, 'new.html')

def create(request):
    token = request.session.get("access_token", "")
    target_id = request.POST['target_id']
    if token != "":
        if (Person.objects.filter(social_id=target_id).exists()):
            person = Person.objects.get(social_id=target_id)
        else:
            session = vk.Session()
            vkapi = vk.API(access_token=token, session = session)
            params = vkapi.users.get(user_ids=target_id)[0]
            person = Person(social_id=target_id, name=params["first_name"], surname=params["last_name"])
        request.session["target_id"] = target_id
        grabber = PhotoGrabber(token)
        urls = grabber.loadPhotos(target_id)
        person.save()
        for url in urls:
            if (not person.photo_set.filter(url=url).exists()):
                response = requests.get(url)
                photo_labels = empty_label#run_inference_on_image(BytesIO(response.content))[0]
                person.photo_set.create(url = url, labels = photo_labels)
        del person
        del grabber
        del urls
        del token
        del target_id
    return render(request, "show.html")

def scanPhoto(request):
    target_id = request.session.get("target_id", "")
    if target_id == "":
        return JsonResponse({"error":"target id not found"})
    if not (Person.objects.filter(social_id=target_id).exists()):
        return JsonResponse({"error":"person does not exist"})

    person = Person.objects.get(social_id=target_id)
    photos_count = person.photo_set.count()
    scaned_count = person.photo_set.filter(~Q(labels=empty_label)).count();
    if person.photo_set.filter(labels=empty_label):
        photo = person.photo_set.filter(labels=empty_label)[0]

        response = requests.get(photo.url)
        photo.labels=run_inference_on_image(BytesIO(response.content))[0]
        photo.save()
        username = request.GET.get('username', None)
        data = {
            'status': "Processing...",
            "value" : scaned_count,
            "max" : photos_count
        }
        return JsonResponse(data)
    else:
        return JsonResponse({"status": "200"})

def makeChart(request):
    target_id = request.session.get("target_id", "")
    if target_id == "":
        return HttpResponse("")
    if not (Person.objects.filter(social_id=target_id).exists()):
        return HttpResponse("")

    person = Person.objects.get(social_id=target_id)
    photos = person.photo_set.all()        
    labels=[photo.labels for photo in photos]

    c = Counter(labels)
    labels
    fig1 = plt.figure()
    ax1 = fig1.add_subplot(111)
    ax1.pie(c.values(), labels=c.keys(), autopct='%1.1f%%', shadow=True, startangle=90)

    imgdata = BytesIO()

    fig1.savefig(imgdata, format='png')
    imgdata.seek(0)  # rewind the data
    plt.close()   

    return HttpResponse(imgdata.getvalue(), content_type='image/png')

def about(request):
    return render(request, 'about.html')

scanner/templates/about.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% endblock %}

scanner/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
		<title>VKScanner</title>
		{% load static %}
		<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
		<link rel="stylesheet" href="{% static "css/style.css" %}">
	</head>

    <body>
		<div class="container">
			<!-- header -->
			<div class="row header">
					<div class="col-md-6 logo">
						<a href="index.html">
							VKScanner
						</a>
					</div>
					<div class="col-md-6 menu text-center">
						<ul>
							<li>
								<a href="https://oauth.vk.com/authorize?client_id=6258947&display=page&scope=6&redirect_uri=https://safe-everglades-40623.herokuapp.com/scanner/login">Войти</a>
							</li>
							<li>
								<a href="">Правила</a>
							</li>
							<li>
								<a href="">FAQ</a>
							</li>
							<li>
								<a href="{% url 'scanner:about' %}">О сайте</a>
							</li>
						</ul>
					</div>
			</div>
			<!-- main -->
			<div class="row main">
				<div class="col-md12">

			{% block content %}{% endblock content %}

				</div>
			</div>
			<!-- footer -->
			<div class="row footer">
				<div class="col-md12">
					<p>
						VKScanner (c) 2017, Все права защищены
					</p>
				</div>
			</div>
		</div>

		<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
		<!-- <script src="{% static 'js/app.js' %}"></script> -->
		{% block javascript %}{% endblock %}
    </body>
</html>

scanner/templates/index.html
{% extends "base.html" %}
{% block content %}
{% load static %}
<div class="row main">
    <div class="col-md12">
        <h1>
                VKScanner - Lorem ipsum dolor sit amet
        </h1>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi beatae eveniet consequatur aspernatur error? Ullam dignissimos aperiam id consectetur amet voluptatibus quisquam aspernatur provident. Eos.
        </p>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius maxime autem libero ducimus iusto blanditiis iste itaque mollitia tempore nihil. Molestias mollitia ipsam omnis, sint architecto error voluptate nam sunt rem, nesciunt ullam dolorum ipsum libero tempore incidunt recusandae quia.
        </p>

        <div class="row carusel text-center">
            <div class="col-md-3 text-center"><img src="{% static "img/carusel-1.jpg" %}"></div>
            <div class="col-md-3 text-center"><img src="{% static "img/carusel-1.jpg" %}"></div>
            <div class="col-md-3 text-center"><img src="{% static "img/carusel-1.jpg" %}"></div>
            <div class="col-md-3 text-center"><img src="{% static "img/carusel-1.jpg" %}"></div>
        </div>

        <p>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores, illo, nesciunt! Velit ullam dignissimos laborum eligendi, tenetur, sunt molestias magni fugiat! Explicabo molestias, provident, iusto quidem ullam nemo soluta nobis perferendis non rerum culpa aliquid adipisci illo quod. Iusto placeat modi perspiciatis voluptatum explicabo odio iure repudiandae rerum, quia non inventore magni perferendis commodi suscipit voluptates culpa, omnis amet accusamus recusandae quod cumque.
        </p>

        <div class="row">
            <div class="col-md-12 login-block text-center">
                <a href="https://oauth.vk.com/authorize?client_id=6258947&display=page&scope=6&redirect_uri=https://safe-everglades-40623.herokuapp.com/scanner/login" class="login-vk">
                    Войти через VK
                </a>
            </div>
        </div>

        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores, illo, nesciunt! Velit ullam dignissimos laborum eligendi, tenetur, sunt molestias magni fugiat! Explicabo molestias, provident, iusto quidem ullam nemo soluta nobis perferendis non rerum culpa aliquid adipisci illo quod. Iusto placeat modi perspiciatis voluptatum explicabo odio iure repudiandae rerum, quia non inventore magni perferendis commodi suscipit voluptates culpa, omnis amet accusamus recusandae quod cumque, in cum doloribus? Aliquid, beatae repellendus deserunt provident illo minus labore doloremque facilis sit! Alias laudantium a labore eius facilis consequatur! Pariatur nemo distinctio delectus eos mollitia enim officiis tempora, dolorum ratione facere vero perferendis adipisci praesentium odio deleniti sunt libero doloribus!</p>
            
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum explicabo earum pariatur fugiat accusantium nostrum iste necessitatibus itaque dolorum deleniti voluptatibus, vero id praesentium debitis ad dicta possimus eum quis labore alias, nulla facere. Mollitia, consequatur dolor vitae. Distinctio necessitatibus possimus, adipisci, quia, laudantium architecto, voluptatum provident officia vitae dignissimos nihil et ipsum consectetur nemo maxime! Expedita nisi optio porro veritatis distinctio ducimus reprehenderit, fuga repellendus aliquid quae sint repudiandae dolore vitae iusto, quo. Reprehenderit.</p>
    </div>
</div>
{% endblock %}

scanner/templates/login.html
<h1>{{ access_token }}</h1>

scanner/templates/new.html
{% extends "base.html" %}
{% block content %}
<div class="input-page">
    <h2>Укажите id пользователя VK</h2>
    <form action="/scanner/scan/" method="post">
        {% csrf_token %}
        <input id="target_id" type="text" name="target_id" value="{{ target_id }}">
        <input type="submit" value="OK">
    </form>
</div>
{% endblock %}

scanner/templates/show.html
{% extends "base.html" %}

{% block javascript %}
<script>
    function makeChart(){
        $.ajax({
            url: "{% url 'scanner:make_chart' %}",
            dataType: 'html',
            success: function (data) {
                $("img").attr("src", "{% url 'scanner:make_chart' %}");
            }
        }); 
    }
    function nextPhoto(){
        $.ajax({
            url: "{% url 'scanner:scan_photo' %}",
            dataType: 'json',
            success: function (data) {
            if (data.status=="200") {
                $("progress").remove();
                makeChart();
            }
            else
                $("progress").attr("max", data.max).attr("value", data.value);
                nextPhoto();
            }
        });

    }
    nextPhoto();

</script>
{% endblock %}

{% block content %}
<img src="{{chart_src}}" alt="">
<progress></progress>
<p></p>
{% endblock %}